version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

  stub1:
    build: ./stub1
    container_name: stub1
    ports:
      - "4001:4001"

  stub2:
    build: ./stub2
    container_name: stub2
    ports:
      - "4002:4002"

volumes:
  ollama_data: