version: '3.8'

services:
  tts:
    build: ./tts
    container_name: tts
    ports:
      - "4010:4010"

  sound:
    build: ./sound
    container_name: sound
    ports:
      - "4011:4011"

  image:
    build: ./image
    container_name: image
    ports:
      - "4012:4012"
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  node-app:
    build: ./node-app
    container_name: node-app
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_URL=http://ollama:11434

volumes:
  ollama_data: